### ISSUE TITLE
运行python run_cnn.py trains时出错

### ISSUE THREAD

**Issue by jiaqiyu543** [gaussic/text-classification-cnn-rnn#110]
Configuring CNN model...
Configuring TensorBoard and Saver...
Loading training and validation data...
Traceback (most recent call last):
  File "run_cnn.py", line 198, in <module>
    train()
  File "run_cnn.py", line 80, in train
    x_train, y_train = process_file(train_dir, word_to_id, cat_to_id, config.seq_length)
  File "/home/niko/Desktop/text-classification-cnn-rnn-master/data/cnews_loader.py", line 107, in process_file
    label_id.append(cat_to_id[labels[i]])
KeyError: 'NHS1\x000\x00p\x0cVeY\x1f(WeYSO-N_\x16Y:W~ve\x19P\x0c)Y1\\/f4llv\x0c\x14lab>f:yS_)Y\x0bNHSl31\\'

**Comment by yichengye310** [comment]
I guess you will need to update /home/niko/Desktop/text-classification-cnn-rnn-master/data/cnews_loader.py with your own labels.

**Comment by SevenMpp** [comment]
请问你这个问题 解决啦嘛 我总是遇到 Traceback (most recent call last):
  File "run_cnn.py", line 16, in <module>
    from data_process import read_vocab, read_category, batch_iter, process_file, build_vocab
  File "F:\Tools\test\cnn_class\data_process.py", line 145, in <module>
    process_file(train_dir,word,cut,max_length=600)
  File "F:\Tools\test\cnn_class\data_process.py", line 115, in process_file
    label_id.append(cat_to_id[labels[i]])
KeyError: '体育'

**Comment by JMF141114** [comment]
> 请问你这个问题 解决啦嘛 我总是遇到 Traceback (most recent call last):
> File "run_cnn.py", line 16, in
> from data_process import read_vocab, read_category, batch_iter, process_file, build_vocab
> File "F:\Tools\test\cnn_class\data_process.py", line 145, in
> process_file(train_dir,word,cut,max_length=600)
> File "F:\Tools\test\cnn_class\data_process.py", line 115, in process_file
> label_id.append(cat_to_id[labels[i]])
> KeyError: '体育'

你的解决了吗？我也遇到这个问题了

**Comment by Gingmzmzx** [comment]
> 请问你这个问题 解决啦嘛 我总是遇到 Traceback (most recent call last): File "run_cnn.py", line 16, in from data_process import read_vocab, read_category, batch_iter, process_file, build_vocab File "F:\Tools\test\cnn_class\data_process.py", line 145, in process_file(train_dir,word,cut,max_length=600) File "F:\Tools\test\cnn_class\data_process.py", line 115, in process_file label_id.append(cat_to_id[labels[i]]) KeyError: '体育'

+1
