### ISSUE TITLE
程序不能正常执行

### ISSUE THREAD

**Issue by pipigou** [gaussic/text-classification-cnn-rnn#17]
在尝试运行程序时，出现了下面的问题：

```bash
D:\Anaconda\envs\tensorflow\python.exe G:/project/python/pycharm/RNN-CNN/run_cnn.py
Traceback (most recent call last):
  File "G:/project/python/pycharm/RNN-CNN/run_cnn.py", line 178, in <module>
    raise ValueError("""usage: python run_cnn.py [train / test]""")
ValueError: usage: python run_cnn.py [train / test]
```

代码时直接copy的（勿喷），数据直接下载的网盘里的，放到了项目的data下面，主要**问题感觉出在sys.argv**上面，打印了一下：

```Python
if __name__ == '__main__':
    print(len(sys.argv))
    print(sys.argv[1])
    if len(sys.argv) != 2 or sys.argv[1] not in ['train', 'test']:
        raise ValueError("""usage: python run_cnn.py [train / test]""")

    print('Configuring CNN model...')
    config = TCNNConfig()
    if not os.path.exists(vocab_dir):  # 如果不存在词汇表，重建
        build_vocab(train_dir, vocab_dir, config.vocab_size)
    categories, cat_to_id = read_category()
    words, word_to_id = read_vocab(vocab_dir)
    config.vocab_size = len(words)
    model = TextCNN(config)

    if sys.argv[1] == 'train':
        train()
    else:
        test()
```

出现的结果在下面：

```bash
D:\Anaconda\envs\tensorflow\python.exe G:/project/python/pycharm/RNN-CNN/run_cnn.py
1
Traceback (most recent call last):
  File "G:/project/python/pycharm/RNN-CNN/run_cnn.py", line 176, in <module>
    print(sys.argv[1])
IndexError: list index out of range
```

希望能够得到你的帮助，谢谢！

**Comment by gaussic** [comment]
### 训练与验证

运行 `python run_cnn.py train`，可以开始训练。

请先仔细的阅读README.md

**Comment by pipigou** [comment]
谢谢，问题已解决
