### ISSUE TITLE
我把predict.py的代码的cnn部分换成了rnn去运行，但是出错说"InvalidArgumentError "

### ISSUE THREAD

**Issue by dapsjj** [gaussic/text-classification-cnn-rnn#64]
**我修改了predict.py，修改后是这样的：**
```
# coding: utf-8

from __future__ import print_function

import os
import tensorflow as tf
import tensorflow.contrib.keras as kr

from rnn_model import TRNNConfig, TextRNN
from data.cnews_loader import read_category, read_vocab

try:
    bool(type(unicode))
except NameError:
    unicode = str

base_dir = 'data/cnews'
vocab_dir = os.path.join(base_dir, 'cnews.vocab.txt')

save_dir = 'checkpoints/textcnn'
save_path = os.path.join(save_dir, 'best_validation')  # 最佳验证结果保存路径


class RnnModel:
    def __init__(self):
        self.config = TRNNConfig()
        self.categories, self.cat_to_id = read_category()
        self.words, self.word_to_id = read_vocab(vocab_dir)
        self.config.vocab_size = len(self.words)
        self.model = TextRNN(self.config)

        self.session = tf.Session()
        self.session.run(tf.global_variables_initializer())
        saver = tf.train.Saver()
        saver.restore(sess=self.session, save_path=save_path)  # 读取保存的模型

    def predict(self, message):
        # 支持不论在python2还是python3下训练的模型都可以在2或者3的环境下运行
        content = unicode(message)
        data = [self.word_to_id[x] for x in content if x in self.word_to_id]

        feed_dict = {
            self.model.input_x: kr.preprocessing.sequence.pad_sequences([data], self.config.seq_length),
            self.model.keep_prob: 1.0
        }

        y_pred_cls = self.session.run(self.model.y_pred_cls, feed_dict=feed_dict)
        return self.categories[y_pred_cls[0]]


if __name__ == '__main__':
    rnn_model = RnnModel()
    test_demo = ['三星ST550以全新的拍摄方式超越了以往任何一款数码相机',
                 '热火vs骑士前瞻：皇帝回乡二番战 东部次席唾手可得新浪体育讯北京时间3月30日7:00']
    for i in test_demo:
        print(rnn_model.predict(i))

```

**而且也重新训练了，但是运行predict.py的时候错误信息是：**
```
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1361, in _do_call
    return fn(*args)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on checkpoints/textcnn\best_validation: Not found: FindFirstFile failed for: checkpoints/textcnn : \udc8ew\udc92肳\udc82ꂽ\udc83p\udc83X\udc82\udcaa\udc8c\udca9\udc82\udca9\udc82\udce8\udc82܂\udcb9\udc82\udcf1\udc81B
; No such process
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/test_opencv/text-classification-cnn-rnn-master/predict.py", line 52, in <module>
    cnn_model = RnnModel()
  File "E:/test_opencv/text-classification-cnn-rnn-master/predict.py", line 35, in __init__
    saver.restore(sess=self.session, save_path=save_path)  # 读取保存的模型
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1760, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1355, in _do_run
    options, run_metadata)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on checkpoints/textcnn\best_validation: Not found: FindFirstFile failed for: checkpoints/textcnn : \udc8ew\udc92肳\udc82ꂽ\udc83p\udc83X\udc82\udcaa\udc8c\udca9\udc82\udca9\udc82\udce8\udc82܂\udcb9\udc82\udcf1\udc81B
; No such process
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "E:/test_opencv/text-classification-cnn-rnn-master/predict.py", line 52, in <module>
    cnn_model = RnnModel()
  File "E:/test_opencv/text-classification-cnn-rnn-master/predict.py", line 34, in __init__
    saver = tf.train.Saver()
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1293, in __init__
    self.build()
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1302, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1339, in _build
    build_save=build_save, build_restore=build_restore)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 796, in _build_internal
    restore_sequentially, reshape)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 449, in _AddRestoreOps
    restore_sequentially)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 847, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1113, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3271, in create_op
    op_def=op_def)
  File "E:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on checkpoints/textcnn\best_validation: Not found: FindFirstFile failed for: checkpoints/textcnn : \udc8ew\udc92肳\udc82ꂽ\udc83p\udc83X\udc82\udcaa\udc8c\udca9\udc82\udca9\udc82\udce8\udc82܂\udcb9\udc82\udcf1\udc81B
; No such process
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

```

**请问如何处理？**

**Comment by vaxilicaihouxian** [comment]
提个小建议 你的标题爆炸 改一下吧

**Comment by gaussic** [comment]
closed
